# Generated by Django 3.1.2 on 2020-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
