# Generated by Django 3.1.2 on 2020-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20201027_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactinfo',
            field=models.CharField(max_length=20),
        ),
    ]
