# Generated by Django 3.1.2 on 2020-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20201027_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(verbose_name=range(0, 10)),
        ),
    ]
