# Generated by Django 3.1.2 on 2020-10-27 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20201027_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
