# Generated by Django 3.1.2 on 2020-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_auto_20201027_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default=2, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
